import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Glob('*.c')

group = DefineGroup('Middle', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
